### PR TITLE
Expose many additional bindings

### PR DESCRIPTION
**Pull request by pcwalton**
Includes bindings to the following:

* Simulations

* Informational strings

* Metrics

* Outlines

* Fetching the font corresponding to a face

r? anyone (I'm not sure who maintains this repo)

### CODE REVIEW

**Comment by pcwalton** [comment]
I don't understand the AppVeyor failure.

**Comment by pcwalton** [comment]
@mbrubeck Do you know what to do about this failure?

**Comment by mbrubeck** [comment]
No idea, sorry. :(

**Comment by pcwalton** [comment]
Does anyone object if I push it through anyway?

I'll leave this for a few days so that anyone can object and/or diagnose the failure. If there are no objections I'll go ahead and push it through. cc @nox @jdm

**Comment by jdm** [comment]
With respect to the failure, it looks similar to https://github.com/rust-lang/rust/issues/48272. We've disabled mingw builds in other repositories when they've exhibited build errors that we haven't been able to diagnose successfully, since for Servo builds we only care about MSVC.

**Comment by mbrubeck** [comment]
r+ to manually merge, and/or switch the appveyor build from gnu to msvc toolchain

**Comment by pcwalton** [comment]
@jdm I'd be happy to change the AppVeyor configuration. Could you provide a link to instructions on how to do this? Thanks!

**Pull request merged**
