### PR TITLE
Bump serde to 1.0 and bump version

### PR DESCRIPTION
**Pull request by Eijebong**
I can't test this locally so I hope it works (appveyor will tell :))

### CODE REVIEW

**Comment by jrmuizel** [comment]
Can you drop the dwrote version related commits?

**Comment by Eijebong** [comment]
You want me to open another PR to bump the version when I'm ready to bump serde in servo ?

**Comment by emilio** [comment]
They're likely needed. @jrmuizel are you fine landing this?

**Comment by Eijebong** [comment]
Ping, This is blocking the webrender PR

**Comment by emilio** [comment]
for the record:

```
14:48 <emilio> jrmuizel: ping, are you fine with landing https://github.com/servo/dwrote-rs/pull/4?
14:49 <@jrmuizel> emilio: yep
14:49 <emilio> jrmuizel: cool, thanks!
```

**Comment by Eijebong** [comment]
Thank you :)

**Pull request merged**
